## Setup

In [30]:
from core.algorithm_shorthands import Shorthands
import h5py
import numpy as np

import os
test = [x[0] for x in os.walk("./")]

with h5py.File('data/training_data.h5', 'r') as f:
    datum = f['berlin_trip']
    graph = np.array(datum, copy=True, dtype=float)
    coordinates = datum.attrs['coordinates']

num_locations = 9
num_days = 2
durations = np.random.randint(1, 96, num_locations) * 15
durations[0] = 0


## Greedy Routing & Greedy Insertion

In [31]:
from core.algorithm_shorthands import Shorthands
Shorthands.greedy(num_locations, num_days, graph, durations, coordinates)

array([6, 7, 5, 8, 3, 2, 0, 4, 1, 0])

## K-Means Clustering & Bruteforce Routing

In [32]:
from algorithms.clustering import Clustering
Shorthands.k_means(num_locations, num_days, graph, durations, coordinates, show_stages=True, routing_algorithm=Clustering.RoutingMethods.BRUTE_FORCE)

array([5, 6, 3, 2, 1, 0, 8, 7, 4, 0])

## Genetic Clustering & Greedy Routing

In [33]:
Shorthands.genetic_clustering(num_locations, num_days, graph, durations, coordinates, generations_per_update=10, routing_algorithm=Clustering.RoutingMethods.GREEDY, seed=seed)

Cluster evolution 0% complete: 0/100 completed. Best evaluation: 46190.0
Cluster evolution 10% complete: 10/100 completed. Best evaluation: 23102.5
Cluster evolution 20% complete: 20/100 completed. Best evaluation: 23102.5
Cluster evolution 30% complete: 30/100 completed. Best evaluation: 23102.5
Cluster evolution 40% complete: 40/100 completed. Best evaluation: 23102.5
Cluster evolution 50% complete: 50/100 completed. Best evaluation: 23102.5
Cluster evolution 60% complete: 60/100 completed. Best evaluation: 23102.5
Cluster evolution 70% complete: 70/100 completed. Best evaluation: 23102.5
Cluster evolution 80% complete: 80/100 completed. Best evaluation: 9212.0
Cluster evolution 90% complete: 90/100 completed. Best evaluation: 9212.0
Cluster evolution complete. Best evaluation: 9212.0


array([4, 3, 8, 2, 0, 6, 7, 5, 1, 0])

## Centroid-based Genetic Clustering & Greedy Routing

In [34]:
Shorthands.genetic_centroid_clustering(num_locations, num_days, graph, durations, coordinates, generations_per_update=10, routing_algorithm=Clustering.RoutingMethods.GREEDY)

Centroid evolution 0% complete: 0/100 completed. Best evaluation: 78310.5
Centroid evolution 10% complete: 10/100 completed. Best evaluation: 78310.5
Centroid evolution 20% complete: 20/100 completed. Best evaluation: 78310.5
Centroid evolution 30% complete: 30/100 completed. Best evaluation: 78310.5
Centroid evolution 40% complete: 40/100 completed. Best evaluation: 78310.5
Centroid evolution 50% complete: 50/100 completed. Best evaluation: 78310.5
Centroid evolution 60% complete: 60/100 completed. Best evaluation: 78310.5
Centroid evolution 70% complete: 70/100 completed. Best evaluation: 78310.5
Centroid evolution 80% complete: 80/100 completed. Best evaluation: 78310.5
Centroid evolution 90% complete: 90/100 completed. Best evaluation: 78310.5
Centroid evolution complete. Best evaluation: 78310.5


array([6, 5, 1, 0, 7, 8, 3, 2, 4, 0])

## Brute Force

In [ ]:
Shorthands.brute_force(num_locations, num_days, graph, durations, coordinates)